### ISSUE TITLE
Slight differences in graphics in Readme.md

### ISSUE THREAD

**Issue by ghost** [ScottMonaghan/Star_Wars_Fall_of_the_Jedi.mrpitiful_fan_edit#11]
My render finally finished. For some reason mine was at 10GB which seems large. The only option I selected was the Use Maximum Render Quality that you had selected in your graphic.

Overall, this was an easy and awesome thing. Totally worth buying the iTunes versions and the DRM removal software to make this work. So, thank you so much for your work putting this together.

The only "Issue" I can find so far besides the font files (the crawl being replaced with Courier looked hilarious) is slight differences in the graphics on the how-to section. I tried replacing them, but the resolution of my Macbook is too low, so my versions looked really small. Whatever computer you're using must have a nice big resolution, or else I can't figure out how you zoomed in to grab the screen shots like that.

Anyways, there are some differences with the file names inside the Zip vs. the graphics. For example, the main file is called Main Draft in your graphics, but the actual file in the Zip is called Star_Wars_Fall_of_the_Jedi.mrpitiful_fan_edit.1.1. I mean, anybody with half a brain could figure this out, but I though I'd mention it.

Thanks again for all your hard work. My friends are having a Fall of the Jedi party at the end of the month.

**Comment by ghost** [comment]
Oh yeah, the ZIP doesn't have an empty 'source' folder, so perhaps that could be included.

**Comment by ScottMonaghan** [comment]
Thanks so much!  I really think you are the first to go through the trouble
to render so I REALLY appreciate it as I went through a lot of effort to
make this doable.

Can you send me a clip of the courier new crawl? I'd like to share that for
hilarity's sake.

Thanks again!

**Comment by ghost** [comment]
https://youtu.be/zq67E2JKiWg :)
