### ISSUE TITLE
Audio clip references will be deleted...

### ISSUE THREAD

**Issue by wdawgnc** [ScottMonaghan/Star_Wars_Fall_of_the_Jedi.mrpitiful_fan_edit#8]
I'm getting the error below when I try to "Replace Footage" using my blu-ray MKV sources that i'm manually converting to MP4 (via ffmpeg).  The MP4 files play correctly and have synced audio. Any ideas?

![image](https://cloud.githubusercontent.com/assets/1768342/23588864/d52e612e-0191-11e7-879d-43ad5f6a97ac.png)

**Comment by ScottMonaghan** [comment]
Sorry, you can try this direct link:
https://drive.google.com/open?id=0BxBqfWxKzHFDbUxRajFaMmVsaW8

**Comment by ScottMonaghan** [comment]
The version I have is edited with the stereo track, not 5.1 or 7.1.  Can you try with stereo audio?
