### ISSUE TITLE
Font error in Adobe Premiere

### ISSUE THREAD

**Issue by ghost** [ScottMonaghan/Star_Wars_Fall_of_the_Jedi.mrpitiful_fan_edit#9]
It says it can't find the font for the crawl.
![screen shot 2017-03-06 at 11 54 51 am](https://cloud.githubusercontent.com/assets/21302237/23620094/c8a257da-0263-11e7-898e-fb4fcf7bd0a9.png)

Also, it said the file was made using an old version of Premiere and had to be converted, so perhaps that's the source for the error.

**Comment by ScottMonaghan** [comment]
Good catch!

Does the rest of the movie render correctly?

Until this renewed interest, I don't know that anyone has actually tried to
render the file with premiere.  I can see about getting you the fonts
tonight.  I'll PM you with more.

**Comment by ScottMonaghan** [comment]
Font download links have been added to the readme.
